### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/symon#177]
## Requirements

- [x] User should be able to enter their email and password
- [x] When Remember me is selected, user should not need to enter credentials anymore after the window is closed.
- [x] If there is no user in the database, it should show the Create new user form.

### Login form

![Login](https://user-images.githubusercontent.com/311343/117281322-cc72c100-ae63-11eb-9839-c14fa9e1e0d5.png)

### Create form

![Create new user](https://user-images.githubusercontent.com/311343/117283196-d72e5580-ae65-11eb-96ad-8fe0a3457245.png)

**Comment by raosan** [comment]
@nicnocquee  in the second task
```
When Remember me is selected, user should not need to enter credentials anymore after the window is closed.
```

does it mean auto login if token still valid, or just autofill the login form?

**Comment by nicnocquee** [comment]
auto login
