### ISSUE TITLE
Create the dashboard sidebar

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/symon#179]
## Requirements

- [x] The sidebar has multiple sections and each sections have items.
- [x] The sidebar should be dynamic: sections and items can be added programmatically.
- [x] For the initial MVP, the sidebar contains 2 sections: `Probes` and `Settings`
- [x] The Setting section contains 2 items: `Account` and `Keys`.

![Screenshot 2021-05-11 at 11 50 16](https://user-images.githubusercontent.com/311343/117796156-189c7780-b24f-11eb-9f90-fe5c90bb44fb.png)

**Comment by kevinhermawan** [comment]
#188
