### ISSUE TITLE
Sidebar menu error when there is a slash in the probe name

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/symon#224]
**Describe the bug**
If there is a slash in the probe name (e.g probe/name/goes/here), it will be treated as a path, making the react router displays Project page.

**To Reproduce**
1. Create a probe with a slash in the probe name in Monika (e.g probe/name/goes/here)
2. Run Monika
3. Wait until the reporting has been done by Symon
4. Open the probe in Symon

**Expected behavior**
It should redirect you to the probe report page.

**Additional context**
N/A

**Comment by kevinhermawan** [comment]
#228
