### ISSUE TITLE
Refresh token is not working

### ISSUE THREAD

**Issue by kevinhermawan** [hyperjumptech/symon#238]
# Summary
The refresh token implementation is not working.

# To reproduce

- login to kaksymon
- wait 5 minutes
- reopen the root page (not the one with /project/org/...).
- data cannot be fetched.

**Comment by haricnugraha** [comment]
It is working as intended. Refresh tokens are credentials used to obtain access tokens. And if the refresh token is expired, the user should repeat the authorization flow.
See OAuth 2.0 [RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-1.5).

**Comment by nicnocquee** [comment]
Reopen this issue. It's still happening.
